name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn typecheck
      - name: Test
        run: yarn test -- --coverage
      - name: Build
        run: yarn build

